// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feorzmuevdcnzajxzavf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlb3J6bXVldmRjbnphanh6YXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzY0MzYsImV4cCI6MjA1NzI1MjQzNn0.6ajR0Zx7xItlN0Xd7wjmfpPwwAOQv9K-VqLcf4H29hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);